### PR TITLE
Make package and add write

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
Interestingly, it turns out that it's totally valid to have files on gdrive with identical names. I suppose when trying to read, we should simply give the most recent one? Right now it will error when more than one entry matches anywhere up the path tree.

**Comment by rabernat** [comment]
> Interestingly, it turns out that it's totally valid to have files on gdrive with identical names. I suppose when trying to read, we should simply give the most recent one? Right now it will error when more than one entry matches anywhere up the path tree.

Correct, this is what I learned. That's why I added this error:

https://github.com/rabernat/fsspec-google-drive/blob/master/gdrivefs.py#L174-L176

I also had to add some stuff to filter out trashed files by default.

Should I merge this?

**Comment by martindurant** [comment]
> Should I merge this?

Sure - it's not exactly released anywhere.
We should discuss that plan, though: would you like this moved to the intake org and a minimal working version prepared for pypi/conda, so we can get people to play with it? Perhaps that's too early, I have hardly put a lot of time into it, and probably neither of us has much to give.

**Comment by martindurant** [comment]
By the way, there is an argument to be made that the default "root" shouldn't be (just) the user's default drive, but the set of shared drives available to the user, including their own drive. For some users that would be just the one thing, so add an extra directory-like layer.

**Comment by rabernat** [comment]
> We should discuss that plan, though: would you like this moved to the intake org and a minimal working version prepared for pypi/conda, so we can get people to play with it?

Yes I think this is the best way forward.

I have added you as a collaborator. Happy to see repo transferred to intake org.

**Comment by martindurant** [comment]
I would need to be an owner to transfer it.

**Pull request merged**
